T_max: 64
a2a_radius: 50.0
a2m_radius: 150.0
accelerator: auto
dataset: argoverse_v2_ACL
devices: 6
dropout: 0.1
head_dim: 16
hidden_dim: 128
input_dim: 2
lambda_contrastive: 1.0
lr: 0.0005
max_epochs: 100
num_agent_layers: 2
num_dec_layers: 2
num_freq_bands: 64
num_future_steps: 30
num_heads: 8
num_historical_steps: 10
num_map_layers: 1
num_modes: 6
num_recurrent_steps: 3
num_t2m_steps: 30
num_workers: 8
output_dim: 2
output_head: false
persistent_workers: true
pin_memory: true
pl2a_radius: 50.0
pl2m_radius: 150.0
pl2pl_radius: 150.0
root: /home/user/Algorithm/QCNet_cum/Code/QCNet_Contrasive/Data/LIS_CP
shuffle: true
submission_dir: ./
submission_file_name: submission
tau: 0.5
test_batch_size: 16
test_processed_dir: null
test_raw_dir: null
theta_n: 0.5
theta_p: 0.33
time_span: 10
train_batch_size: 16
train_processed_dir: null
train_raw_dir: null
val_batch_size: 16
val_processed_dir: null
val_raw_dir: null
weight_decay: 0.0001
